### ISSUE TITLE
checkout not loading

### ISSUE THREAD

**Issue by tobiasolge** [schrammel-codes/magento2-epc-qr-code#1]
in version 2.4.6-p6 checkout is not loading for me.
I cannot see any exceptions in the log.

**Comment by aschrammel** [comment]
Hi @tobiasolge 

Thanks for your report.

I'm not able reproduce the issue on a Magento 2.4.6-p6 vanilla installation.
Could you please retry on a vanilla instance and report if your issue persists?

**Comment by aschrammel** [comment]
Going to close this due to missing feedback.
